### PR TITLE
fix: memoization issue when using different search keys

### LINKED ISSUE #109: Memoized index's causing index with more than one search on a page
We are using this within react, and we're seeing on our search page that the fields list doesn't work properly with multiple searches. We have one for a global search and another for a table filter. However, on the global it doesn't search on all the fields we have listed in the dependencies. We suspect this is due to the memoization on the data index, it's not updating the two dependencies when we switch to the search instances

### PR DESCRIPTION
**Pull request by yann510**
closes #109

### CODE REVIEW

File: ss-search/src/lib/ss-search.ts [hunk 1]
```diff
@@ -8,37 +8,40 @@ export const normalize = (text: string | undefined) =>
...
+            }
+
+            return value
+          })
+          .reduce((a, b) => a + b, '')
+      )
+      .map((x) => normalize(x))
+  },
+  (elements, searchableKeys) => [elements, searchableKeys]
+)
```
Comment (Tcheetox) [inline ss-search/src/lib/ss-search.ts:44]: Hey @yann510, did you check that you are actually hitting lodash cache with this default resolver? From reading lodash' doc, I feel like this won't hit the cache because the reference to the created array will be different each time we call search. Again, I didn't dig much further, but that's why I suggested we could perhaps pass an optional string cache key as part of the search(). Anyway, thanks for looking at this so quickly, I won't come bother you again 👍

Comment (yann510) [reply ss-search/src/lib/ss-search.ts:44]: You are absolutely correct, I implemented this too fast.
I've taken your suggestion into account and added an optional cache key along with the relevant documentation to explain why and when to use it.

Please bother me any time, I'm happy to help and thanks for reporting this bug :)
Here's the updated PR: https://github.com/yann510/ss-search/pull/111
